In [1]:
# Modules to install
# pip install scikit-clean pandas numpy sklearn

# Importo librerías

In [2]:
import numpy as np
import pandas as pd
# Stablish random_seed/state for reproducibility
rs=33

# Preparo datos

Importo a continuación un conjunto variado de datasets basícos ofrecidos por sklearn:

In [3]:
import pandas as pd
from sklearn.datasets import load_iris, load_wine, load_digits, load_breast_cancer

# 1) Cargar datasets sklearn
raw_datasets = [
    ("iris", load_iris()),
    ("wine", load_wine()),
    ("digits", load_digits()),
    ("breast_cancer", load_breast_cancer()),
]

# 2) Convertir a DataFrames con target en la última columna
dfs = []
dfs_names = []

for name, d in raw_datasets:
    X = pd.DataFrame(d.data, columns=d.feature_names)
    y = pd.Series(d.target, name="target")
    df = pd.concat([X, y], axis=1)  # target al final
    dfs.append(df)
    dfs_names.append(name)

# dfs -> lista de DataFrames
# dfs_names -> lista de nombres en el mismo orden

# (Opcional) ver shapes y columnas
for name, df in zip(dfs_names, dfs):
    print(f"{name:14s} shape={df.shape}  target_col={df.columns[-1]!r}")

iris           shape=(150, 5)  target_col='target'
wine           shape=(178, 14)  target_col='target'
digits         shape=(1797, 65)  target_col='target'
breast_cancer  shape=(569, 31)  target_col='target'

# Testeo filtros

## Random Uniform Label Change

Testeo a continuación el desempeño de diferentes técnicas de filtrado amplicando un intercambio aleatorio de las etiquetas de la columna target, ello sobre los difderentes datasets antes importados y haciendo uso de diferentes niveles de ruido.

### EnsembleFilter

In [4]:
import numpy as np
import pandas as pd

from sklearn.base import BaseEstimator
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

from numpy.random import randint, seed

from filters import *
from noiseData import *
from testFuncs import *


ens_filter_sampler = EnsembleFiltering(
    estimators=[
        GaussianNB(),
        RandomForestClassifier(random_state=33),
    ],
    cv=5,
    mode="consensus",
    # threshold=0.75,
    action="remove",
    random_state=33,
)

# --- ejecutar TU función exactamente ---
noise_levels = [0.0, 0.05, 0.10, 0.20, 0.30]

res = urlf_test_in_dfs(
    dfs=dfs,
    dfs_names=dfs_names,
    noise_levels=noise_levels,
    rs=33,
    filter=ens_filter_sampler,
    model=KNeighborsClassifier(),
    sc=StandardScaler(),
    k_cv=5
)

Processing iris with noise level=0.0.
Processing iris with noise level=0.05.
Processing iris with noise level=0.1.
Processing iris with noise level=0.2.
Processing iris with noise level=0.3.


Processing wine with noise level=0.0.
Processing wine with noise level=0.05.
Processing wine with noise level=0.1.
Processing wine with noise level=0.2.
Processing wine with noise level=0.3.


Processing digits with noise level=0.0.
Processing digits with noise level=0.05.
Processing digits with noise level=0.1.
Processing digits with noise level=0.2.
Processing digits with noise level=0.3.


Processing breast_cancer with noise level=0.0.
Processing breast_cancer with noise level=0.05.
Processing breast_cancer with noise level=0.1.
Processing breast_cancer with noise level=0.2.
Processing breast_cancer with noise level=0.3.

In [5]:
pd.DataFrame(res["iris"])

    df_name  noise_pct       Acc    BalAcc  f1_macro  Prec_macro  Rec_macro
0      iris      -1.00  0.960000  0.960000  0.959832    0.963434   0.960000
1   iris_nf       0.00  0.960000  0.960000  0.959832    0.963434   0.960000
2    iris_f       0.00  0.966667  0.966667  0.966617    0.968485   0.966667
3   iris_nf       0.05  0.893333  0.893333  0.890612    0.904397   0.893333
4    iris_f       0.05  0.906667  0.906667  0.904215    0.916063   0.906667
5   iris_nf       0.10  0.840000  0.835556  0.830300    0.877803   0.835556
6    iris_f       0.10  0.880000  0.877037  0.871587    0.908258   0.877037
7   iris_nf       0.20  0.733333  0.729360  0.700252    0.747309   0.729360
8    iris_f       0.20  0.786667  0.784175  0.747349    0.776926   0.784175
9   iris_nf       0.30  0.606667  0.608687  0.561497    0.566878   0.608687
10   iris_f       0.30  0.706667  0.710909  0.656816    0.662643   0.710909

In [6]:
pd.DataFrame(res["wine"])

    df_name  noise_pct       Acc    BalAcc  f1_macro  Prec_macro  Rec_macro
0      wine      -1.00  0.949365  0.958413  0.951160    0.951542   0.958413
1   wine_nf       0.00  0.949365  0.958413  0.951160    0.951542   0.958413
2    wine_f       0.00  0.949365  0.958413  0.951160    0.951542   0.958413
3   wine_nf       0.05  0.909841  0.915079  0.909307    0.914579   0.915079
4    wine_f       0.05  0.909841  0.917725  0.910837    0.914915   0.917725
5   wine_nf       0.10  0.842381  0.844339  0.833841    0.855401   0.844339
6    wine_f       0.10  0.853651  0.856508  0.845537    0.864211   0.856508
7   wine_nf       0.20  0.730000  0.727407  0.693018    0.715101   0.727407
8    wine_f       0.20  0.785873  0.788360  0.760442    0.796119   0.788360
9   wine_nf       0.30  0.611746  0.594693  0.550920    0.599959   0.594693
10   wine_f       0.30  0.673810  0.664347  0.618351    0.671905   0.664347

In [7]:
pd.DataFrame(res["digits"])

      df_name  noise_pct       Acc    BalAcc  f1_macro  Prec_macro  Rec_macro
0      digits      -1.00  0.944362  0.944077  0.943982    0.948030   0.944077
1   digits_nf       0.00  0.944362  0.944077  0.943982    0.948030   0.944077
2    digits_f       0.00  0.941026  0.940743  0.940623    0.945051   0.940743
3   digits_nf       0.05  0.897625  0.897481  0.897387    0.902015   0.897481
4    digits_f       0.05  0.895399  0.895177  0.895213    0.899849   0.895177
5   digits_nf       0.10  0.847549  0.847688  0.847846    0.852656   0.847688
6    digits_f       0.10  0.841984  0.842084  0.842139    0.847794   0.842084
7   digits_nf       0.20  0.750176  0.750281  0.750140    0.757519   0.750281
8    digits_f       0.20  0.754627  0.755264  0.754100    0.762552   0.755264
9   digits_nf       0.30  0.665579  0.666330  0.664894    0.671116   0.666330
10   digits_f       0.30  0.687278  0.688183  0.686852    0.693022   0.688183

In [8]:
pd.DataFrame(res["breast_cancer"])

,df_name,noise_pct,Acc,BalAcc,f1_macro,Prec_macro,Rec_macro
0,breast_cancer,-1.00,0.964850,0.958548,0.962058,0.967163,0.958548
1,breast_cancer_nf,0.00,0.964850,0.958548,0.962058,0.967163,0.958548
2,breast_cancer_f,0.00,0.964866,0.955741,0.961804,0.970142,0.955741
3,breast_cancer_nf,0.05,0.906816,0.895681,0.900727,0.909177,0.895681
4,breast_cancer_f,0.05,0.919127,0.905053,0.913214,0.927951,0.905053
5,breast_cancer_nf,0.10,0.854091,0.840540,0.845741,0.858456,0.840540
6,breast_cancer_f,0.10,0.864617,0.846909,0.854960,0.877714,0.846909
7,breast_cancer_nf,0.20,0.752166,0.734154,0.736803,0.755032,0.734154
8,breast_cancer_f,0.20,0.783807,0.764427,0.769265,0.796452,0.764427
9,breast_cancer_nf,0.30,0.676681,0.665554,0.663414,0.684381,0.665554
10,breast_cancer_f,0.30,0.717016,0.701392,0.699261,0.738448,0.701392

### ClassificationFilter

In [9]:
import numpy as np
import pandas as pd

from sklearn.base import BaseEstimator
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

from numpy.random import randint, seed

from filters import *
from noiseData import *
from testFuncs import *


ens_filter_sampler = ClassificationFilter(
    estimator = KNeighborsClassifier()
)

# --- ejecutar TU función exactamente ---
noise_levels = [0.0, 0.05, 0.10, 0.20, 0.30]

res = urlf_test_in_dfs(
    dfs=dfs,
    dfs_names=dfs_names,
    noise_levels=noise_levels,
    rs=33,
    filter=ens_filter_sampler,
    model=KNeighborsClassifier(),
    sc=StandardScaler(),
    k_cv=5
)

Processing iris with noise level=0.0.
Processing iris with noise level=0.05.
Processing iris with noise level=0.1.
Processing iris with noise level=0.2.
Processing iris with noise level=0.3.


Processing wine with noise level=0.0.
Processing wine with noise level=0.05.
Processing wine with noise level=0.1.
Processing wine with noise level=0.2.
Processing wine with noise level=0.3.


Processing digits with noise level=0.0.
Processing digits with noise level=0.05.
Processing digits with noise level=0.1.
Processing digits with noise level=0.2.
Processing digits with noise level=0.3.


Processing breast_cancer with noise level=0.0.
Processing breast_cancer with noise level=0.05.
Processing breast_cancer with noise level=0.1.
Processing breast_cancer with noise level=0.2.
Processing breast_cancer with noise level=0.3.

In [10]:
pd.DataFrame(res["iris"])

    df_name  noise_pct       Acc    BalAcc  f1_macro  Prec_macro  Rec_macro
0      iris      -1.00  0.960000  0.960000  0.959832    0.963434   0.960000
1   iris_nf       0.00  0.960000  0.960000  0.959832    0.963434   0.960000
2    iris_f       0.00  0.966667  0.966667  0.966617    0.968485   0.966667
3   iris_nf       0.05  0.893333  0.893333  0.890612    0.904397   0.893333
4    iris_f       0.05  0.906667  0.906667  0.904215    0.916063   0.906667
5   iris_nf       0.10  0.840000  0.835556  0.830300    0.877803   0.835556
6    iris_f       0.10  0.853333  0.850370  0.844614    0.889058   0.850370
7   iris_nf       0.20  0.733333  0.729360  0.700252    0.747309   0.729360
8    iris_f       0.20  0.773333  0.770101  0.735847    0.769741   0.770101
9   iris_nf       0.30  0.606667  0.608687  0.561497    0.566878   0.608687
10   iris_f       0.30  0.686667  0.690168  0.639947    0.650243   0.690168

In [11]:
pd.DataFrame(res["wine"])

    df_name  noise_pct       Acc    BalAcc  f1_macro  Prec_macro  Rec_macro
0      wine      -1.00  0.949365  0.958413  0.951160    0.951542   0.958413
1   wine_nf       0.00  0.949365  0.958413  0.951160    0.951542   0.958413
2    wine_f       0.00  0.949683  0.954762  0.951348    0.952038   0.954762
3   wine_nf       0.05  0.909841  0.915079  0.909307    0.914579   0.915079
4    wine_f       0.05  0.899048  0.908042  0.901260    0.908553   0.908042
5   wine_nf       0.10  0.842381  0.844339  0.833841    0.855401   0.844339
6    wine_f       0.10  0.831429  0.835556  0.823660    0.844980   0.835556
7   wine_nf       0.20  0.730000  0.727407  0.693018    0.715101   0.727407
8    wine_f       0.20  0.758254  0.756085  0.723179    0.747108   0.756085
9   wine_nf       0.30  0.611746  0.594693  0.550920    0.599959   0.594693
10   wine_f       0.30  0.623651  0.601758  0.550099    0.646425   0.601758

In [12]:
pd.DataFrame(res["digits"])

      df_name  noise_pct       Acc    BalAcc  f1_macro  Prec_macro  Rec_macro
0      digits      -1.00  0.944362  0.944077  0.943982    0.948030   0.944077
1   digits_nf       0.00  0.944362  0.944077  0.943982    0.948030   0.944077
2    digits_f       0.00  0.941583  0.941299  0.941193    0.945697   0.941299
3   digits_nf       0.05  0.897625  0.897481  0.897387    0.902015   0.897481
4    digits_f       0.05  0.898182  0.898053  0.898081    0.903001   0.898053
5   digits_nf       0.10  0.847549  0.847688  0.847846    0.852656   0.847688
6    digits_f       0.10  0.844208  0.844307  0.844210    0.849793   0.844307
7   digits_nf       0.20  0.750176  0.750281  0.750140    0.757519   0.750281
8    digits_f       0.20  0.753513  0.753892  0.753250    0.760205   0.753892
9   digits_nf       0.30  0.665579  0.666330  0.664894    0.671116   0.666330
10   digits_f       0.30  0.687830  0.688692  0.687595    0.692942   0.688692

In [13]:
pd.DataFrame(res["breast_cancer"])

,df_name,noise_pct,Acc,BalAcc,f1_macro,Prec_macro,Rec_macro
0,breast_cancer,-1.00,0.964850,0.958548,0.962058,0.967163,0.958548
1,breast_cancer_nf,0.00,0.964850,0.958548,0.962058,0.967163,0.958548
2,breast_cancer_f,0.00,0.959571,0.949626,0.956096,0.965188,0.949626
3,breast_cancer_nf,0.05,0.906816,0.895681,0.900727,0.909177,0.895681
4,breast_cancer_f,0.05,0.908570,0.892492,0.901401,0.919045,0.892492
5,breast_cancer_nf,0.10,0.854091,0.840540,0.845741,0.858456,0.840540
6,breast_cancer_f,0.10,0.869880,0.852703,0.860838,0.882380,0.852703
7,breast_cancer_nf,0.20,0.752166,0.734154,0.736803,0.755032,0.734154
8,breast_cancer_f,0.20,0.790840,0.772130,0.777026,0.803107,0.772130
9,breast_cancer_nf,0.30,0.676681,0.665554,0.663414,0.684381,0.665554
10,breast_cancer_f,0.30,0.711753,0.697724,0.696298,0.727424,0.697724

### IterativePartitioningFilter

In [14]:
import numpy as np
import pandas as pd

from sklearn.base import BaseEstimator
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

from numpy.random import randint, seed

from filters import *
from noiseData import *
from testFuncs import *


ens_filter_sampler = IterativePartitioningFilter()

# --- ejecutar TU función exactamente ---
noise_levels = [0.0, 0.05, 0.10, 0.20, 0.30]

res = urlf_test_in_dfs(
    dfs=dfs,
    dfs_names=dfs_names,
    noise_levels=noise_levels,
    rs=33,
    filter=ens_filter_sampler,
    model=KNeighborsClassifier(),
    sc=StandardScaler(),
    k_cv=5
)

Processing iris with noise level=0.0.
Processing iris with noise level=0.05.
Processing iris with noise level=0.1.
Processing iris with noise level=0.2.
Processing iris with noise level=0.3.


Processing wine with noise level=0.0.
Processing wine with noise level=0.05.
Processing wine with noise level=0.1.
Processing wine with noise level=0.2.
Processing wine with noise level=0.3.

/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 8 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=10.
  warnings.warn(

Processing digits with noise level=0.0.

/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=10.
  warnings.warn(

Processing digits with noise level=0.05.

/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 8 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(

Processing digits with noise level=0.1.

/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 8 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 9 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 9 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  warnings.warn(

Processing digits with noise level=0.2.

/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 8 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(

Processing digits with noise level=0.3.

/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 9 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=10.
  warnings.warn(
/home/juamp/Documents/Master/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(

Processing breast_cancer with noise level=0.0.
Processing breast_cancer with noise level=0.05.
Processing breast_cancer with noise level=0.1.
Processing breast_cancer with noise level=0.2.
Processing breast_cancer with noise level=0.3.

In [15]:
pd.DataFrame(res["iris"])

    df_name  noise_pct       Acc    BalAcc  f1_macro  Prec_macro  Rec_macro
0      iris      -1.00  0.960000  0.960000  0.959832    0.963434   0.960000
1   iris_nf       0.00  0.960000  0.960000  0.959832    0.963434   0.960000
2    iris_f       0.00  0.953333  0.953333  0.953047    0.958384   0.953333
3   iris_nf       0.05  0.893333  0.893333  0.890612    0.904397   0.893333
4    iris_f       0.05  0.893333  0.893333  0.891265    0.902660   0.893333
5   iris_nf       0.10  0.840000  0.835556  0.830300    0.877803   0.835556
6    iris_f       0.10  0.866667  0.863704  0.859646    0.898517   0.863704
7   iris_nf       0.20  0.733333  0.729360  0.700252    0.747309   0.729360
8    iris_f       0.20  0.793333  0.790842  0.754578    0.785634   0.790842
9   iris_nf       0.30  0.606667  0.608687  0.561497    0.566878   0.608687
10   iris_f       0.30  0.693333  0.696094  0.644709    0.648228   0.696094

In [16]:
pd.DataFrame(res["wine"])

    df_name  noise_pct       Acc    BalAcc  f1_macro  Prec_macro  Rec_macro
0      wine      -1.00  0.949365  0.958413  0.951160    0.951542   0.958413
1   wine_nf       0.00  0.949365  0.958413  0.951160    0.951542   0.958413
2    wine_f       0.00  0.938413  0.947460  0.940790    0.944237   0.947460
3   wine_nf       0.05  0.909841  0.915079  0.909307    0.914579   0.915079
4    wine_f       0.05  0.915714  0.922487  0.916586    0.923007   0.922487
5   wine_nf       0.10  0.842381  0.844339  0.833841    0.855401   0.844339
6    wine_f       0.10  0.853810  0.855714  0.846313    0.871607   0.855714
7   wine_nf       0.20  0.730000  0.727407  0.693018    0.715101   0.727407
8    wine_f       0.20  0.746825  0.755661  0.725248    0.742910   0.755661
9   wine_nf       0.30  0.611746  0.594693  0.550920    0.599959   0.594693
10   wine_f       0.30  0.532540  0.489841  0.422434    0.447499   0.489841

In [17]:
pd.DataFrame(res["digits"])

      df_name  noise_pct       Acc    BalAcc  f1_macro  Prec_macro  Rec_macro
0      digits      -1.00  0.944362  0.944077  0.943982    0.948030   0.944077
1   digits_nf       0.00  0.944362  0.944077  0.943982    0.948030   0.944077
2    digits_f       0.00  0.849759  0.847640  0.820369    0.811053   0.847640
3   digits_nf       0.05  0.897625  0.897481  0.897387    0.902015   0.897481
4    digits_f       0.05  0.775206  0.775021  0.739400    0.726744   0.775021
5   digits_nf       0.10  0.847549  0.847688  0.847846    0.852656   0.847688
6    digits_f       0.10  0.742936  0.742388  0.706191    0.680572   0.742388
7   digits_nf       0.20  0.750176  0.750281  0.750140    0.757519   0.750281
8    digits_f       0.20  0.660026  0.661681  0.628667    0.609685   0.661681
9   digits_nf       0.30  0.665579  0.666330  0.664894    0.671116   0.666330
10   digits_f       0.30  0.547021  0.550132  0.492604    0.460748   0.550132

In [18]:
pd.DataFrame(res["breast_cancer"])

,df_name,noise_pct,Acc,BalAcc,f1_macro,Prec_macro,Rec_macro
0,breast_cancer,-1.00,0.964850,0.958548,0.962058,0.967163,0.958548
1,breast_cancer_nf,0.00,0.964850,0.958548,0.962058,0.967163,0.958548
2,breast_cancer_f,0.00,0.949061,0.934609,0.944098,0.958073,0.934609
3,breast_cancer_nf,0.05,0.906816,0.895681,0.900727,0.909177,0.895681
4,breast_cancer_f,0.05,0.910340,0.892295,0.902889,0.923393,0.892295
5,breast_cancer_nf,0.10,0.854091,0.840540,0.845741,0.858456,0.840540
6,breast_cancer_f,0.10,0.869912,0.850116,0.859873,0.887661,0.850116
7,breast_cancer_nf,0.20,0.752166,0.734154,0.736803,0.755032,0.734154
8,breast_cancer_f,0.20,0.773265,0.751030,0.756040,0.789014,0.751030
9,breast_cancer_nf,0.30,0.676681,0.665554,0.663414,0.684381,0.665554
10,breast_cancer_f,0.30,0.709983,0.694244,0.692773,0.728179,0.694244